language: node_js
node_js:
  - '6'
deploy:
  provider: firebase
  token:
    secure: process.env.FIREBASE_WEB_API_KEY
  project: "anyharvest"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
env:
  - CXX=g++-4.8
sudo: required
before_script: npm i
after_script: npm run coveralls
script:
  - npm test
  - npm run lint
